<?xml version="1.0" encoding="ISO-8859-1" ?>

<!DOCTYPE persona [
        <!ELEMENT persona (datos, comentario?)>
        <!ATTLIST persona
                nacimiento CDATA #REQUIRED>
        <!ELEMENT datos (nombre, apellidos, dni)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT apellidos (#PCDATA)>
        <!ELEMENT dni (#PCDATA)>
        <!ELEMENT comentario (#PCDATA)>
        ]>

<persona nacimiento="1999-10-20">
    <datos>
        <nombre>Pepe</nombre>
        <apellidos>Garcia</apellidos>
        <dni>25390952</dni>
    </datos>
    <comentario>buena gente...</comentario>
</persona>